<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class CustomersSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'customer_id'     => 'CUS' . str_pad('1', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'John Doe',
                'customer_phone'  => '081234567890',
                'customer_address'=> 'Jl. Merdeka No. 10, Jakarta Pusat',
                'customer_status' => 'active',
                'created_at'      => '2024-12-15 09:30:00',
                'updated_at'      => '2024-12-15 09:30:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('2', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Jane Smith',
                'customer_phone'  => '082345678901',
                'customer_address'=> 'Jl. Raya No. 5, Jakarta Selatan',
                'customer_status' => 'active',
                'created_at'      => '2024-12-16 10:45:00',
                'updated_at'      => '2024-12-16 10:45:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('3', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Robert Brown',
                'customer_phone'  => '085678901234',
                'customer_address'=> 'Jl. Sudirman No. 22, Bandung',
                'customer_status' => 'inactive',
                'created_at'      => '2024-12-17 11:20:00',
                'updated_at'      => '2025-01-05 14:30:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('4', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Emily White',
                'customer_phone'  => '089876543210',
                'customer_address'=> 'Jl. Agung No. 12, Surabaya',
                'customer_status' => 'active',
                'created_at'      => '2024-12-18 13:15:00',
                'updated_at'      => '2024-12-18 13:15:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('5', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Michael Johnson',
                'customer_phone'  => '081122334455',
                'customer_address'=> 'Jl. Pahlawan No. 8, Medan',
                'customer_status' => 'active',
                'created_at'      => '2024-12-19 09:00:00',
                'updated_at'      => '2024-12-19 09:00:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('6', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Sarah Williams',
                'customer_phone'  => '082233445566',
                'customer_address'=> 'Jl. Diponegoro No. 15, Yogyakarta',
                'customer_status' => 'active',
                'created_at'      => '2024-12-20 14:30:00',
                'updated_at'      => '2024-12-20 14:30:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('7', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'David Miller',
                'customer_phone'  => '083344556677',
                'customer_address'=> 'Jl. Gatot Subroto No. 25, Jakarta Selatan',
                'customer_status' => 'inactive',
                'created_at'      => '2024-12-21 10:15:00',
                'updated_at'      => '2025-01-10 09:45:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('8', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Amanda Jones',
                'customer_phone'  => '084455667788',
                'customer_address'=> 'Jl. Ahmad Yani No. 30, Surabaya',
                'customer_status' => 'active',
                'created_at'      => '2024-12-22 11:45:00',
                'updated_at'      => '2024-12-22 11:45:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('9', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Thomas Wilson',
                'customer_phone'  => '085566778899',
                'customer_address'=> 'Jl. Veteran No. 18, Malang',
                'customer_status' => 'active',
                'created_at'      => '2024-12-23 13:30:00',
                'updated_at'      => '2024-12-23 13:30:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('10', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Lisa Anderson',
                'customer_phone'  => '086677889900',
                'customer_address'=> 'Jl. Thamrin No. 7, Jakarta Pusat',
                'customer_status' => 'active',
                'created_at'      => '2024-12-24 09:20:00',
                'updated_at'      => '2024-12-24 09:20:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('11', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Richard Taylor',
                'customer_phone'  => '087788990011',
                'customer_address'=> 'Jl. Pemuda No. 22, Semarang',
                'customer_status' => 'active',
                'created_at'      => '2024-12-26 10:10:00',
                'updated_at'      => '2024-12-26 10:10:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('12', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Jennifer Davis',
                'customer_phone'  => '088899001122',
                'customer_address'=> 'Jl. Asia Afrika No. 14, Bandung',
                'customer_status' => 'inactive',
                'created_at'      => '2024-12-27 14:25:00',
                'updated_at'      => '2025-01-15 11:20:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('13', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Charles Martinez',
                'customer_phone'  => '089900112233',
                'customer_address'=> 'Jl. Kartini No. 9, Denpasar',
                'customer_status' => 'active',
                'created_at'      => '2024-12-28 15:40:00',
                'updated_at'      => '2024-12-28 15:40:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('14', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Patricia Robinson',
                'customer_phone'  => '081100223344',
                'customer_address'=> 'Jl. Hayam Wuruk No. 11, Jakarta Barat',
                'customer_status' => 'active',
                'created_at'      => '2024-12-29 09:55:00',
                'updated_at'      => '2024-12-29 09:55:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('15', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Daniel Clark',
                'customer_phone'  => '082211334455',
                'customer_address'=> 'Jl. Gajah Mada No. 20, Yogyakarta',
                'customer_status' => 'active',
                'created_at'      => '2024-12-30 11:15:00',
                'updated_at'      => '2024-12-30 11:15:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('16', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Elizabeth Rodriguez',
                'customer_phone'  => '083322445566',
                'customer_address'=> 'Jl. Imam Bonjol No. 16, Semarang',
                'customer_status' => 'inactive',
                'created_at'      => '2024-12-31 13:40:00',
                'updated_at'      => '2025-01-20 10:30:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('17', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Matthew Lewis',
                'customer_phone'  => '084433556677',
                'customer_address'=> 'Jl. Riau No. 24, Bandung',
                'customer_status' => 'active',
                'created_at'      => '2025-01-02 10:05:00',
                'updated_at'      => '2025-01-02 10:05:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('18', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Nancy Lee',
                'customer_phone'  => '085544667788',
                'customer_address'=> 'Jl. Panglima Sudirman No. 28, Surabaya',
                'customer_status' => 'active',
                'created_at'      => '2025-01-03 11:25:00',
                'updated_at'      => '2025-01-03 11:25:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('19', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'George Walker',
                'customer_phone'  => '086655778899',
                'customer_address'=> 'Jl. Juanda No. 17, Medan',
                'customer_status' => 'active',
                'created_at'      => '2025-01-04 14:50:00',
                'updated_at'      => '2025-01-04 14:50:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('20', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Sandra Hall',
                'customer_phone'  => '087766889900',
                'customer_address'=> 'Jl. Kebon Sirih No. 13, Jakarta Pusat',
                'customer_status' => 'active',
                'created_at'      => '2025-01-05 09:30:00',
                'updated_at'      => '2025-01-05 09:30:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('21', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Kenneth Young',
                'customer_phone'  => '088877990011',
                'customer_address'=> 'Jl. Cendrawasih No. 19, Makassar',
                'customer_status' => 'inactive',
                'created_at'      => '2025-01-06 10:40:00',
                'updated_at'      => '2025-02-01 13:15:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('22', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Donna Allen',
                'customer_phone'  => '089988001122',
                'customer_address'=> 'Jl. Mangga Dua No. 21, Jakarta Utara',
                'customer_status' => 'active',
                'created_at'      => '2025-01-07 13:20:00',
                'updated_at'      => '2025-01-07 13:20:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('23', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Ronald Scott',
                'customer_phone'  => '081199002233',
                'customer_address'=> 'Jl. Kawi No. 26, Malang',
                'customer_status' => 'active',
                'created_at'      => '2025-01-08 15:10:00',
                'updated_at'      => '2025-01-08 15:10:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('24', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Carol Green',
                'customer_phone'  => '082200113344',
                'customer_address'=> 'Jl. Antasari No. 23, Banjarmasin',
                'customer_status' => 'active',
                'created_at'      => '2025-01-09 09:45:00',
                'updated_at'      => '2025-01-09 09:45:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('25', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Steven Baker',
                'customer_phone'  => '083311224455',
                'customer_address'=> 'Jl. Teuku Umar No. 15, Denpasar',
                'customer_status' => 'inactive',
                'created_at'      => '2025-01-10 11:35:00',
                'updated_at'      => '2025-02-05 14:20:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('26', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Kimberly Adams',
                'customer_phone'  => '084422335566',
                'customer_address'=> 'Jl. Sisingamangaraja No. 27, Medan',
                'customer_status' => 'active',
                'created_at'      => '2025-01-11 14:15:00',
                'updated_at'      => '2025-01-11 14:15:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('27', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Edward Nelson',
                'customer_phone'  => '085533446677',
                'customer_address'=> 'Jl. Pasar Baru No. 12, Jakarta Pusat',
                'customer_status' => 'active',
                'created_at'      => '2025-01-12 10:25:00',
                'updated_at'      => '2025-01-12 10:25:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('28', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Helen Carter',
                'customer_phone'  => '086644557788',
                'customer_address'=> 'Jl. Merdeka No. 31, Bandung',
                'customer_status' => 'active',
                'created_at'      => '2025-01-13 11:50:00',
                'updated_at'      => '2025-01-13 11:50:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('29', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Frank Mitchell',
                'customer_phone'  => '087755668899',
                'customer_address'=> 'Jl. Diponegoro No. 29, Surabaya',
                'customer_status' => 'inactive',
                'created_at'      => '2025-01-14 13:05:00',
                'updated_at'      => '2025-02-10 09:40:00',
            ],
            [
                'customer_id'     => 'CUS' . str_pad('30', 6, '0', STR_PAD_LEFT),
                'customer_name'   => 'Michelle Perez',
                'customer_phone'  => '088866779900',
                'customer_address'=> 'Jl. Sudirman No. 33, Jakarta Selatan',
                'customer_status' => 'active',
                'created_at'      => '2025-01-15 15:30:00',
                'updated_at'      => '2025-01-15 15:30:00',
            ],
        ];

        $this->db->table('customers')->insertBatch($data);
    }
}