<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductsSeeder extends Seeder
{
    public function run()
    {
        $data = [
            // ===== MAKANAN RINGAN (CAT000001) =====
            [
                'product_id'         => 'PDT' . str_pad('1', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Chitato 80g',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000001', 
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000001',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('2', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Taro 75g',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000001',
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000002',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('3', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Lays Original 75g',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000001',
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000003',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('4', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Qtela Singkong 85g',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000001',
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000004',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('5', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Pringles Original 107g',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000001',
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000005',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            
            // ===== MAKANAN INSTAN (CAT000002) =====
            [
                'product_id'         => 'PDT' . str_pad('6', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Indomie Goreng 85g',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000002',  
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000006',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('7', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Mie Sedaap Goreng 90g',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000002',  
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000007',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('8', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Indomie Soto 75g',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000002',  
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000006',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('9', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Pop Mie Ayam 75g',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000002',  
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000008',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('10', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Buristo Beef 100g',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000002',  
                'product_status'     => 'inactive',
                'supplier_id'        => 'SUP000009',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],

            // ===== MAKANAN BEKU (CAT000003) =====
            [
                'product_id'         => 'PDT' . str_pad('11', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Ayam Fillet 1kg',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000003',  
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000001',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('12', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Daging Sapi 500g',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000003',  
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000002',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('13', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Nugget Ayam 500g',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000003',  
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000003',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('14', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Bakso Sapi 300g',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000003',  
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000004',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('15', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Sosis Ayam 500g',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000003',  
                'product_status'     => 'inactive',
                'supplier_id'        => 'SUP000005',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            
            // ===== MINUMAN SODA (CAT000004) =====
            [
                'product_id'         => 'PDT' . str_pad('16', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Coca-Cola 330ml',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000004',  
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000006',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('17', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Pepsi 330ml',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000004',  
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000007',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('18', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Sprite 390ml',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000004',  
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000006',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('19', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Fanta 390ml',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000004',  
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000006',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('20', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'A&W Root Beer 330ml',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000004',  
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000008',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],

            // ===== MINUMAN TEH (CAT000005) =====
            [
                'product_id'         => 'PDT' . str_pad('21', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Teh Botol Sosro 450ml',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000005',  
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000009',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('22', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Teh Pucuk Harum 350ml',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000005', 
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000010',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('23', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Teh Kotak 300ml',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000005', 
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000009',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('24', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Teh Gelas 200ml',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000005', 
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000010',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('25', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Fruit Tea 350ml',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000005', 
                'product_status'     => 'inactive',
                'supplier_id'        => 'SUP000009',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            
            // ===== MINUMAN JUS (CAT000006) =====
            [
                'product_id'         => 'PDT' . str_pad('26', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Buavita Jeruk 250ml',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000006',  
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000001',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('27', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Minute Maid Pulpy 350ml',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000006', 
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000002',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('28', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'UC1000 Vitamin Orange 140ml',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000006', 
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000003',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('29', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Floridina 350ml',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000006', 
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000004',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'product_id'         => 'PDT' . str_pad('30', 6, '0', STR_PAD_LEFT),
                'product_name'       => 'Buavita Mangga 250ml',  
                'buying_price'       => 0,
                'selling_price'      => 0,
                'product_stock'      => 0,
                'product_category_id'=> 'CAT000006', 
                'product_status'     => 'active',
                'supplier_id'        => 'SUP000001',
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('products')->insertBatch($data);
    }
}